### ISSUE TITLE
Place two fab buttons side by side

### ISSUE THREAD

**Issue by ruisebastiao** [Ecodev/fab-speed-dial#1]
How can i put two fab buttons side by side like, if i put two fab i get the following: 
![fab](https://user-images.githubusercontent.com/5761011/38873211-25613872-424d-11e8-9916-804981671743.gif)
i get a space with the length of the actions buttons.
souldn't the actions container be in an overlay?

**Comment by PowerKiKi** [comment]
[Material design guideline](https://material.io/guidelines/components/buttons-floating-action-button.html#buttons-floating-action-button-floating-action-button) suggest to have a single FAB button on the entire page:

> Only one floating action button is recommended per screen to increase its prominence. It should represent only the most common action.

So I would try to think about alternatives for your need. But if that's something you would like to do anyway, please consider contributing overlay support. As it would definitely be an improvement.

**Comment by sambaptista** [comment]
Last update 1.0.1 changed that. 

Now component is sized by the trigger's dimension, ignoring the actions list that overflow now over content.

**Comment by ddtch** [comment]
Actually, I use multiple fab icons on page, in every row of my table there is a fab button which hides a lot of options for row.
