### ISSUE TITLE
Not working with angular 7 project.

### ISSUE THREAD

**Issue by johannesjo** [Ecodev/fab-speed-dial#11]
Not sure, but it it seems that there is an issue with the latest build. I can import the module, but the components don't seem to be available anywhere.The html gets not parsed to the component and the linting in webstorm also hows me that `eco-fab-speed-dial` etc are unknown html tags.

**Comment by miller45** [comment]
Just tried it with a fresh ng7 project (angular-cli) and it works...Did you add the @angular/material  stuff? This required for this to work. (see https://material.angular.io/guide/getting-started)

**Comment by johannesjo** [comment]
I did. Maybe I'm missing some modules. I'll check and get back to you.

Ramon Klein <notifications@github.com> schrieb am Fr., 26. Okt. 2018, 20:43:

**Comment by johannesjo** [comment]
Interesting. Just copied over the contents of the app component over too, so all functions used are also there. Now it works. It's interesting because no error whatsoever was thrown before.

**Comment by johannesjo** [comment]
Maybe it makes sense to adjust the example in the Readme in a way that copy and paste works fine?

**Comment by johannesjo** [comment]
Maybe it makes sense to adjust the example in the Readme in a way that copy and paste works fine?
