### ISSUE TITLE
Support other kind of mat buttons

### ISSUE THREAD

**Issue by Albhaku** [Ecodev/fab-speed-dial#13]
Hi, this is well done job, works pretty fine and seems nice. I just want to ask if you could change the trigger selector from "mat-button" to some other word.

What I want is be able to use the button bot not in fab button. (I know this is the purpose, but could be cool if you allow to use it outside fab buttons"

Thanks

**Comment by Albhaku** [comment]
Haha, I just figured out that I can add mat-fab and then override with mat-button. In my case just need to add some css but it's ok.

Thanks, sry.

**Comment by idzer0lis** [comment]
> Haha, I just figured out that I can add mat-fab and then override with mat-button. In my case just need to add some css but it's ok.
> 
> Thanks, sry.

Can you post extra details?
I find it wrong that you cant have different buttons. Im thinking of modifying the source code...
