### ISSUE TITLE
How to open on hover

### ISSUE THREAD

**Issue by ubugnu** [Ecodev/fab-speed-dial#17]
It seems that there is no doc on how to open speed dial on hover, nor on how to open it programatically.
We can find examples here https://github.com/Ecodev/fab-speed-dial/blob/master/src/app/app.component.html by it would be nice to have them on readme page.

**Comment by PowerKiKi** [comment]
See the code of the demo and notice the use of `mouseenter` and `mouseleave` events:

https://github.com/Ecodev/fab-speed-dial/blob/23298835c9ec52454cd1e66a03bd8ce9bd4ed237/src/app/app.component.html#L67
