### ISSUE TITLE
Dial button does not close menu in Angular 16.1.0 after second press

### ISSUE THREAD

**Issue by mszymcza** [Ecodev/fab-speed-dial#174]
Scenario:
When I press button menu opens, but after second press it doesn't close. 

Check in Angular 16.1.0 with this dependencies:
"dependencies": {
    "@angular/animations": "^16.1.0",
    "@angular/common": "^16.1.0",
    "@angular/compiler": "^16.1.0",
    "@angular/core": "^16.1.0",
    "@angular/forms": "^16.1.0",
    "@angular/platform-browser": "^16.1.0",
    "@angular/platform-browser-dynamic": "^16.1.0",
    "@angular/router": "^16.1.0",
    "@ecodev/fab-speed-dial": "15.0.0",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.13.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^16.1.6",
    "@angular/cli": "~16.1.6",
    "@angular/compiler-cli": "^16.1.0",
    "@types/jasmine": "~4.3.0",
    "jasmine-core": "~4.6.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.2.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.1.0",
    "typescript": "~5.1.3"
}

**Comment by PowerKiKi** [comment]
Cannot reproduce on https://ecodev.github.io/fab-speed-dial. Please, provide a reproduction case on stackblitz.com

**Comment by mszymcza** [comment]
Sorry, probably I forgot about one of material dependencies, because when I copy code from repo: https://github.com/Ecodev/fab-speed-dial/blob/master/src/app/app.component.ts close button works. 
You can close this issue.
Link to stackblitz:
https://stackblitz.com/edit/stackblitz-starters-ci6aff?file=src%2Fmain.ts
