### ISSUE TITLE
open=false doesn't work

### ISSUE THREAD

**Issue by kojilab** [Ecodev/fab-speed-dial#18]
[open]="false" still shows the menu without the labels. This is with Angular 7.

**Comment by PowerKiKi** [comment]
Cannot reproduce. The demo page does not exhibit the issue and the following minimal template, will not either:

```html
<div style="margin-top: 12em;">

        <eco-fab-speed-dial [open]="false">

            <eco-fab-speed-dial-trigger>
                <button mat-fab>
                    <mat-icon>add</mat-icon>
                </button>
            </eco-fab-speed-dial-trigger>

            <eco-fab-speed-dial-actions>
                <button mat-mini-fab>
                    <mat-icon>search</mat-icon>
                </button>
                <button mat-mini-fab>
                    <mat-icon>edit</mat-icon>
                </button>
                <button mat-mini-fab>
                    <mat-icon>home</mat-icon>
                </button>
            </eco-fab-speed-dial-actions>

        </eco-fab-speed-dial>

</div>
```

It will correctly show a button with nothing else. And upon click will open and show correct content, as well as hide everything when clicked again:

![open-false mp4](https://user-images.githubusercontent.com/72603/59804950-ec6a6b80-9343-11e9-89f1-dd93c7c13e75.gif)

Provide a [reprex](https://stackoverflow.com/help/minimal-reproducible-example) if you need more help.
