### ISSUE TITLE
Component not working with content projection

### ISSUE THREAD

**Issue by GeorgeKnap** [Ecodev/fab-speed-dial#19]
Please take a look at the stackblitz:
https://stackblitz.com/edit/angular-pzpveo

When the buttons are rendered via content projection, the speed dial fab stays open and does not work properly.
Kindly appreciate any help if there is a bug on my side.

**Comment by PowerKiKi** [comment]
I am not familiar with content projection and it is not something we use at all. So I am afraid I won't be able to help. But if you are able to create a PR, covered by tests, to fix whatever is broken, I'll merge it.

**Comment by GeorgeKnap** [comment]
I've done some debuggin and I see the the issue is in `EcoFabSpeedDialActionsComponent`
```
@ContentChildren(MatButton) buttons: QueryList<MatButton>;
```
Apparently ContentChildren does not query ng-content from projected content. (neither `{descendants: true}` and `ngProjectAs` helps).

[explanation is in this comment](https://github.com/angular/angular/issues/20810#issuecomment-401341413)
[https://github.com/dart-lang/angular/issues/195](https://github.com/dart-lang/angular/issues/195)

That means the projection works well but the logic of showing/hiding fab items cannot work due to the query.

Unless you want try find a way how to rewrite it wrapping this lib seems not possible at this point.

**Comment by PowerKiKi** [comment]
Thanks for the feedback, I'll be closing as wontfix as it is unlikely we will invest time in that. But if somebody else find some workaround, feel free to continue the discussion.
