### ISSUE TITLE
Feature request: Extended Fab

### ISSUE THREAD

**Issue by no-more** [Ecodev/fab-speed-dial#2]
Hello,

The plugin looks great, thanks a lot.
Do you have any plan to implement [Extended Fab](https://material.io/design/components/buttons-floating-action-button.html#extended-fab) ?

Thanks

**Comment by PowerKiKi** [comment]
We don't have immediate need for that. So it probably won't be implemented by us anytime soon. But if you are willing to contribute the feature, it would probably be merged as long as it follow the spec.

I'll close the issue for now, but feel free to keep the discussion going if need be.
