### ISSUE TITLE
Angular 9 support

### ISSUE THREAD

**Issue by FranciscoKnebel** [Ecodev/fab-speed-dial#26]
Hello, Angular 9 is now released, and:
```
@ecodev/fab-speed-dial" has an incompatible peer dependency to "@angular/material" (requires "^8.1.2", would install "9.0.0").
```

Haven't tested yet if anything breaks, but upgrading from Angular 8.2 to 9 throws this warning.

Thanks :)

**Comment by PowerKiKi** [comment]
Fixed in [5.0.0](https://github.com/Ecodev/fab-speed-dial/releases/tag/5.0.0) that should be released on npm in a few minutes

**Comment by PowerKiKi** [comment]
So that ended up being [5.0.2](https://www.npmjs.com/package/@ecodev/fab-speed-dial/v/5.0.2) on npm...

**Comment by FranciscoKnebel** [comment]
Thanks for the prompt fix!
Appreciate it.

Em sáb, 8 de fev de 2020 01:46, Adrien Crivelli <notifications@github.com>
escreveu:
