### ISSUE TITLE
An accessor cannot be declared in an ambient context

### ISSUE THREAD

**Issue by didiokener** [Ecodev/fab-speed-dial#27]
Hi there, this error is occurring on my project when I run it:

ERROR in ../node_modules/@ecodev/fab-speed-dial/lib/fab-speed-dial.d.ts:44:9 - error TS1086: An accessor cannot be declared in an ambient context.
     get fixed(): boolean;
           ~~~~~
../node_modules/@ecodev/fab-speed-dial/lib/fab-speed-dial.d.ts:45:9 - error TS1086: An accessor cannot be declared in an ambient context.
     set fixed(fixed: boolean);
           ~~~~~
../node_modules/@ecodev/fab-speed-dial/lib/fab-speed-dial.d.ts:49:9 - error TS1086: An accessor cannot be declared in an ambient context.
     get open(): boolean;
           ~~~~
../node_modules/@ecodev/fab-speed-dial/lib/fab-speed-dial.d.ts:50:9 - error TS1086: An accessor cannot be declared in an ambient context.
     set open(open: boolean);
           ~~~~
../node_modules/@ecodev/fab-speed-dial/lib/fab-speed-dial.d.ts:54:9 - error TS1086: An accessor cannot be declared in an ambient context.
     get direction(): Direction;
           ~~~~~~~~~
../node_modules/@ecodev/fab-speed-dial/lib/fab-speed-dial.d.ts:55:9 - error TS1086: An accessor cannot be declared in an ambient context.
     set direction(direction: Direction);
           ~~~~~~~~~
../node_modules/@ecodev/fab-speed-dial/lib/fab-speed-dial.d.ts:59:9 - error TS1086: An accessor cannot be declared in an ambient context.
     get animationMode(): AnimationMode;
           ~~~~~~~~~~~~~
../node_modules/@ecodev/fab-speed-dial/lib/fab-speed-dial.d.ts:60:9 - error TS1086: An accessor cannot be declared in an ambient context.
     set animationMode(animationMode: AnimationMode);
           ~~~~~~~~~~~~~
../node_modules/@ecodev/fab-speed-dial/lib/fab-speed-dial.d.ts:82:9 - error TS1086: An accessor cannot be declared in an ambient context.
     get sp(): boolean;

This is my package.json
`"devDependencies": {
    "@angular-builders/custom-webpack": "8.4.1",
    "@angular-devkit/build-angular": "^0.803.23",
    "@angular/cli": "8.3.21",
    "@angular/common": "8.2.14",
    "@angular/compiler": "8.2.14",
    "@angular/compiler-cli": "8.2.14",
    "@angular/core": "8.2.14",
    "@angular/language-service": "8.2.14",
    "@angular/platform-browser": "8.2.14",
    "@angular/platform-browser-dynamic": "8.2.14",
    "@angular/router": "8.2.14",
    "@ngx-translate/core": "11.0.1",
    "@ngx-translate/http-loader": "4.0.0",
    "@types/jasmine": "3.5.0",
    "@types/jasminewd2": "2.0.8",
    "@types/mocha": "5.2.7",
    "@types/node": "12.12.21",
    "chai": "4.2.0",
    "codelyzer": "5.2.1",
    "conventional-changelog-cli": "2.0.31",
    "core-js": "3.6.0",
    "electron": "^7.1.8",
    "electron-builder": "^22.3.2",
    "electron-reload": "1.5.0",
    "jasmine-core": "3.5.0",
    "jasmine-spec-reporter": "4.2.1",
    "karma": "4.4.1",
    "karma-chrome-launcher": "3.1.0",
    "karma-coverage-istanbul-reporter": "2.1.1",
    "karma-jasmine": "2.0.1",
    "karma-jasmine-html-reporter": "1.4.2",
    "mocha": "6.2.2",
    "npm-run-all": "4.1.5",
    "rxjs": "^6.5.3",
    "spectron": "9.0.0",
    "ts-node": "8.5.4",
    "tslint": "5.20.1",
    "typescript": "^3.5.3",
    "wait-on": "3.3.0",
    "webdriver-manager": "12.1.7",
    "zone.js": "0.10.2"
  },
  "engines": {
    "node": ">=10.9.0"
  },
  "dependencies": {
    "@angular/animations": "^8.2.14",
    "@angular/cdk": "~8.2.3",
    "@angular/fire": "^5.2.3",
    "@angular/forms": "^8.2.14",
    "@angular/material": "^8.2.3",
    "@angular/material-moment-adapter": "^8.2.3",
    "@aspnet/signalr": "^1.1.4",
    "@ecodev/fab-speed-dial": "^5.0.2",
    "@fortawesome/angular-fontawesome": "^0.5.0",
    "@fortawesome/fontawesome-svg-core": "^1.2.26",
    "@fortawesome/free-solid-svg-icons": "^5.12.0",
    "@swimlane/ngx-charts": "^13.0.1",
    "electron-log": "^4.0.0",
    "electron-store": "^5.1.0",
    "electron-updater": "^4.2.0",
    "electron-util": "^0.13.1",
    "firebase": "^7.6.1",
    "jsonwebtoken": "^8.5.1",
    "material-design-icons": "^3.0.1",
    "moment": "^2.24.0",
    "ngx-currency": "^2.2.1",
    "ngx-file-helpers": "^2.0.0",
    "ngx-float-button": "^1.0.0",
    "ngx-mask": "^8.1.7",
    "ngx-mat-select-search": "^2.1.1",
    "ngx-spinner": "^8.1.0",
    "node-machine-id": "^1.1.12",
    "primeflex": "^1.0.0",
    "primeicons": "^2.0.0",
    "primeng": "^9.0.0-rc.2",
    "request": "^2.88.0",
    "vanilla-text-mask": "^5.1.1"
  }`

and my tsconfig.json
`{
  "compileOnSave": false,
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "removeComments": true,
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "es2016",
      "es2015",
      "dom"
    ]
  },
  "include": [
    "main.ts",
    "src/**/*"
  ],
  "exclude": [
    "node_modules"
  ]
}`

**Comment by PowerKiKi** [comment]
You are using fab-speed-dial 5.0.2 which [requires Angular 9.0+](https://github.com/Ecodev/fab-speed-dial/blob/043ab0594ed7b279fa8a713411faa1d273e0171f/projects/fab-speed-dial/package.json#L7-L9). But you are using Angular 8. Yarn/npm will warn you about invalid peer dependencies.

You must upgrade to Angular 9 or down grade to fab-speed-dial 4.0.0.
