### ISSUE TITLE
Outside Click, does not remove the 'eco-opened' css Class

### ISSUE THREAD

**Issue by luis-teixeira** [Ecodev/fab-speed-dial#30]
When clicking outside the FAB the Action Items are collapse behind the Trigger, but the '' eco-opened '' class remains there.

**Comment by PowerKiKi** [comment]
Cannot reproduce on demo page. Reopen with a [reprex](https://stackoverflow.com/help/minimal-reproducible-example) if you can.

![class-is-remove-on-close mp4](https://user-images.githubusercontent.com/72603/78229098-7cac2280-750a-11ea-8923-7a55ca383154.gif)
