### ISSUE TITLE
Document is not defined 

### ISSUE THREAD

**Issue by fzucchet** [Ecodev/fab-speed-dial#40]
Hi!
I try to use the ecodev but i get this error when add the lib :
typescript ERROR Error: Uncaught (in promise): ReferenceError: Document is not defined ReferenceError: Document is not defined

**Comment by fzucchet** [comment]
i use it with nativescript (android deploy)

**Comment by PowerKiKi** [comment]
AFAIK we already follow best-practices and use document injection to be as compatible as possible (eg with SSR):

```ts
@Inject(DOCUMENT) private document: Document
```

I am not familiar with NativeScript, you'll have to debug on your own
