### ISSUE TITLE
Feature request: base z-index configurable

### ISSUE THREAD

**Issue by pfosser** [Ecodev/fab-speed-dial#46]
Hi, it would be nice to have support for a configurable base z-index, for the action items above all. For the items, it's set programmatically, so it overwrites any style given from outside.

**Comment by PowerKiKi** [comment]
What about hardcoding `Z_INDEX_ITEM` to something very high. Now it's 23, so let's say 999 ?

**Comment by pfosser** [comment]
You're never safe with hard coded values, you could always bump into other libraries with a hardcoded value greater than yours. Anyways, I managed to overcome the problem which originated the request. 
Thanks anyway

**Comment by sambaptista** [comment]
> Now it's 23, so let's say 999 ?

This would lead the FAB buttons to be displayed over the Material overlays, and it really should be avoided. 

I agree with homemade solutions for everybody's specific use cases.
