### ISSUE TITLE
Angular Material v11 support

### ISSUE THREAD

**Issue by MursalovAltun** [Ecodev/fab-speed-dial#70]
Currently when updating to angular material v11 it fails with:
Package "@ecodev/fab-speed-dial" has an incompatible peer dependency to "@angular/material" (requires "^10.0.0", would install "11.1.0").

Please update dependencies for v11 support

**Comment by PowerKiKi** [comment]
fab-speed-dial since [7.0.0](https://github.com/Ecodev/fab-speed-dial/releases/tag/7.0.0) support Angular 11, as you can see in : https://github.com/Ecodev/fab-speed-dial/blob/e7dc9d0af1a81df25c4d576dd2f76ee3cc6ab68b/projects/fab-speed-dial/package.json#L6-L10
